version: 0.2

phases:
  pre_build:
    commands:
      - echo `ls`
      - pip install -r requirements.txt --target ./
      - echo `ls`
  build:
    commands:
      - python -m unittest discover -s tst
artifacts:
  secondary-artifacts:
    buildArtifact:
      files:
        - '**/*'
      name: buildArtifact
    configArtifact:
      files:
        - 'user-config.json'
      name: configArtifact
