version: 0.2

phases:
  pre_build:
    commands:
      - echo `ls`
      - pip install -r requirements.txt --target ./
      - echo `ls`
  build:
    commands:
      - python -m unittest discover -s tst
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    configArtifact:
      files:
        - 'user-config.json'
      name: 'configArtifact'
