version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - python3 --version
      - pip install --upgrade pip
      - python3 -m pip install nox
  pre_build:
    commands:
      - python3 --version
      - pip install --upgrade pip
      - mkdir build
  build:
    commands:
      - python3 --version
      - pip install --upgrade pip
      - ls
      - nox
      - pip install -r requirements.txt --target ./
      - ls
reports:
  unit-test:
    files:
      - 'junit.xml'
    base-directory: 'build/unit-test/xml'
    file-format: JUNITXML
  code-coverage:
    files:
      - 'coverage-report.xml'
    base-directory: 'build/coverage/xml'
    file-format: COBERTURAXML
artifacts:
  name: builderArtifact
  secondary-artifacts:
    buildArtifact:
      files:
        - '**/*'
      exclude-paths:
        - 'build/**/*'
        - 'tests/**/*'
        - '.coverage'
        - 'README.md'
        - 'requirements.txt'
        - '.gitignore'
        - '.nox/**/*'
        - '.mypy_cache/**/*'
        - '.pytest_cache/**/*'
      name: buildArtifact
    configArtifact:
      files:
        - 'user-config.json'
      name: configArtifact
