version: 0.2

phases:
  install:
    - apt-get install -y python3-venv
  pre_build:
    - echo `ls`
    - pip install -r requirements.txt
    - echo `ls`
    -
  build:
    commands:
      - python -m unittest discover -s tst
artifacts:
  files:
    - '**/*'
