from enum import Enum


class CampsiteType(Enum):
    WALK_TO = 'WALK TO'
    STANDARD_NONELECTRIC = 'STANDARD NONELECTRIC'
    RV_ELECTRIC = 'RV ELECTRIC'
    TENT_ONLY_NONELECTRIC = 'TENT ONLY NONELECTRIC'
    STANDARD_ELECTRIC = 'STANDARD ELECTRIC'
    GROUP_TENT_ONLY_AREA_NONELECTRIC = 'GROUP TENT ONLY AREA NONELECTRIC'
    MANAGEMENT = 'MANAGEMENT'
    RV_NONELECTRIC = 'RV NONELECTRIC'
